language: node:js
nodejs:
  - stable
branches:
  only:
  - build_gh
after_success:
  - bash scripts/deploy.sh
deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  edge: true
  keep_history: true
  on:
    branch: build_gh